- name: configure {{ component }} playbook
  hosts: "{{ component }}"
  become: yes
  roles: # this will automatically load the folder which is present in current working directory
  - "{{ component }}"
                